[package]
name = "rust_testing"
version = "0.1.0"
authors = ["Gyula Gubacsi <gyula.gubacsi@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "testing"
path = "testing/stack_test.rs"

[dependencies]
